mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")), 
    #  polls.urls주소로 연결됨
    path("admin/", admin.site.urls),
]

# 최상위 url에서 url파싱후 받아서 path별로 나누어주고
# 앱이 여러개 있으면 url여러개를 파싱후 각각 주소에 할당해줌
# http://127.0.0.1:8000/polls/

polls/urls.py
from django.urls import path

from . import views

# 장고에서 지원하는 url 패턴의 규칙


# 13.URL의 이름공간 정하기추가
app_name = "polls"

# 15 제너릭 뷰 수정
# urlpatterns = [
#     # ex: /polls/
#     path("", views.index, name="index"),
#     # 주소창에 url패턴이 아닌 name값을 입력하면 됨
   
    
#     # ex: /polls/5/
#     # 수정
#     # path("<int:question_id>/", views.detail, name="detail"),
#     # question_id로 5를 호출하면 5의 상세페이지가 url주소에 출력됨
#       # views.py의 question_id와 같아야함
      
      
#     # 12.URL 제거하기  수정
#     # path("specifics/ <int:question_id>/", views.detail, name="detail"),
    
#     # 13.URL의 이름공간 정하기 수정
#     #  다시 원상 되돌림
#     path("<int:question_id>/", views.detail, name="detail"),
    
    
    
#     # ex: /polls/5/results/
#     path("<int:question_id>/results/", views.results, name="results"),
#      # views.py의 question_id와 같아야함
    
#     # ex: /polls/5/vote/
#     path("<int:question_id>/vote/", views.vote, name="vote"),
# ]


# 15 제너릭 뷰 수정
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

# Django에서 제네릭 뷰(Generic Views)는 일반적인 웹 개발 패턴을 구현하는 데 도움을 주기 위해 미리 정의된 뷰 클래스를 제공하는 기능이다
# 제네릭 뷰는 재사용 가능하며, 일반적인 작업을 처리하는 데 필요한 코드를 줄일 수 있도록 도와준다. 
# 주로 모델 데이터를 기반으로 하는 CRUD (Create, Read, Update, Delete) 작업을 지원한다.

# 두 번째와 세 번째 패턴의 경로 문자열에서 일치한 패턴의 이름이 <question_id>에서 <pk>로 변경되었다. 
# 이것은 우리가 DetailView 제네릭 뷰를 사용하여 detail() 및 results() 뷰를 대체할 것이기 때문에 필요한 조치이다. 
# DetailView는 URL에서 캡처된 기본 키(primary key) 값을 'pk'라는 이름으로 기대하고 있다."

# 간단히 말해, Django의 DetailView는 URL에서 캡처된 객체의 기본 키를 'pk'라는 이름으로 예상한다. 
# 따라서 URL 패턴에서 이 이름을 사용하는 것이 일반적으로 권장되는 관례이다. 
# 문장에서 언급된 <question_id>는 URL에서 캡처되는 질문 객체의 기본 키를 나타낸다. 
# 이를 <pk>로 변경함으로써 DetailView가 정상적으로 동작하도록 하는 것이다.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# 29.관리자 변경 목록(change list) 커스터마이징 추가
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text 
       
    # 19버그수정
    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    def was_published_recently(self):
     now = timezone.now()
     return now - datetime.timedelta(days=1) <= self.pub_date <= now
# timezone.now()를 사용하여 현재 시간을 가져온다.
# datetime.timedelta(days=1)을 사용하여 1일의 시간 간격을 생성
# now - datetime.timedelta(days=1)는 현재 날짜와 1일 전의 날짜를 계산
# self.pub_date는 해당 Question 객체의 발행일자(pub_date 필드)이다.
# self.pub_date가 1일 전의 날짜 이상이면서 현재 날짜 이하인지를 확인한다.
# 만약 조건이 참이면 True를 반환하고, 그렇지 않으면 False를 반환한다.
# Question 객체의 pub_date가 최근 24시간 이내에 있는지를 판단하여 그 결과를 불리언 값으로 반환한다.


# 29.관리자 변경 목록(change list) 커스터마이징 추가
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now 

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)   
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. 성공이야")

# Create your views here.
# view내부의 문구가 클라이언트에게 화면으로 전달

polls/templates/polls/detail.html
    <!--HTML 폼의 기본 개념

    각 질문 선택 항목에 대한 라디오 버튼을 표시

    각 라디오 버튼의 value는 연관된 질문 선택 항목의 ID
    
    각 라디오 버튼의 name은 "choice"
     
    즉, 누군가가 라디오 버튼 중 하나를 선택하여 폼을 제출하면, POST 데이터 인 choice=#을 보낼 것이다. 
    
    여기서 #은 선택한 항목의 ID-->

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}

{#양식의 action``을 ``{% url 'polls:vote' question.id %}``로 설정하고, ``method="post"``로 설정한다.#} 
    
{#이 양식을 제출하는 행위는 데이터 서버측을 변화시키기 때문에 ``method="post" (``method=”get”``과 반대로)를 사용하는 것은 매우 중요하다.#}
 
{#데이터 서버측을 변경하는 양식을 만들 때마다 ``method=”post”``를 사용한다#}

{#이 팁은 Django에만 국한된 것이 아니라 일반적인 좋은 웹 개발 관행#}


{#POST 양식을 만들고 있기 때문에(데이터를 수정하는 효과가 있을 수 있음), 교차 사이트 요청 위조(Cross Site Request Forgeries)에 대해 보호하는 유용한 시스템을 가지고 있다. #}

{#내부 URL을 대상으로 하는 모든 POST 양식은 {% csrf_token %} 템플릿 태그를 사용해야 한다.#}


    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <!--forloop.counter 는 for 태그가 반복 한 횟수를 나타낸다.-->
    <input type="submit" value="선택">
    </form>

polls/templates/polls/detail_1.html
<h1>{{ question.question_text }}</h1>
<!--question 객체의 question_text 속성을 출력하여 HTML <h1> 요소에 질문 텍스트를 표시.-->
   
<ul>
{% for choice in question.choice_set.all %}
 <!--question 객체의 choice_set을 사용하여 해당 질문의 외래키에 속한 모든 선택지를 가져온다.-->
<!--자주쓰는 코드방식이라 외움-->
 <!--for 루프를 사용하여 각 선택지의 choice_text 속성을 출력하여 HTML <ul> 밑에 리스트 아이템(<li>)으로 표시-->
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
<!--템플릿 시스템은 변수의 속성에 접근하기 위해 점-탐색(dot-lookup) 문법을 사용한다. 예제의 {{ question.question_text }} 구문을 보면, Django는 먼저 question 객체에 대해 사전형으로 탐색한다. 
    탐색에 실패하게 되면 속성값으로 탐색한다. 만약 속성 탐색에도 실패한다면 리스트의 인덱스 탐색을 시도하게 됩니다.-->

polls/templates/polls/index.html
<!--25. 앱의 모양과 느낌 추가-->
{% load static %}
{#{% static %} 템플릿 태그는 정적 파일의 절대 URL을 생성합니다.#}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{#정적 파일을 서로 연결할 때는 항상 **상대 경로**를 사용해야 한다. 그러면 정적 파일의 여러 경로를 수정할 필요 없이 STATIC_URL`( :ttag:`static 템플릿 태그에서 URL을 생성하는 데 사용됨)을 변경할 수 있다.#}

{% if latest_question_list %}
<!--views.py로부터 받아서-->
    <ul>
    {% for question in latest_question_list %}

    <!--12.하드코딩된 URL 제거-->
        <!--<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
    
        <!--12.하드코딩된 URL 제거수정-->
    <!--polls.urls 모듈에 서술된 URL 의 정의를 탐색하는 식으로 동작-->  
    {#<li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>#}
 
        
        <!--13.URL의 이름공간 정하기-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

        <!--http://127.0.0.1:8000/polls/2/-->

    {% endfor %}
    </ul>
    <!--화면에 리스트로 출력-->

{% else %}
    <p>No polls are available.</p>
{% endif %}

<!--내용없으면 No polls are available.출력-->

polls/templates/polls/index_1.html
{% if latest_question_list %}
<!--views.py로부터 받아서-->
    <ul>
    {% for question in latest_question_list %}

    <!--12.하드코딩된 URL 제거-->
        <!--<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
    
        <!--12.하드코딩된 URL 제거수정-->
    <!--polls.urls 모듈에 서술된 URL 의 정의를 탐색하는 식으로 동작-->  
    {#<li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>#}
 
        
        <!--13.URL의 이름공간 정하기-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

        <!--http://127.0.0.1:8000/polls/2/-->

    {% endfor %}
    </ul>
    <!--화면에 리스트로 출력-->

{% else %}
    <p>No polls are available.</p>
{% endif %}

<!--내용없으면 No polls are available.출력-->

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">재선택</a>